### ISSUE TITLE
[BUG] large images without specified width overflows (`is-readable-line-width`)

### ISSUE THREAD

**Issue by rolemadelen** [gasparschott/obsidian-continuous-mode#10]
obsidian version: v1.5.11

Thank you for the great plugin, but I think I spotted a bug in the preview mode.

When you add an image (e.g. 1000x1000) in the note without specifying the width, obsidian's default setting displays the image correctly because `max-width: var(--img-max-width)` is applied in the image.

![image](https://github.com/gasparschott/obsidian-continuous-mode/assets/101682300/92744d01-c448-4b97-b472-51fb2a015337)

But when continous-mode is enabled and preview it (edit mode displays it fine), it overrides the `max-width` and displays the 100% width overflowing the readable line width: 

in continous-mode - preview:
![image](https://github.com/gasparschott/obsidian-continuous-mode/assets/101682300/0f85be0a-c4e6-40fe-ae52-30402493e4db)

---

I've checked the code and `--file-margins` value doesn't seem to be passed down correctly from the parent element, because it's just setting the image's `max-width` as `100%`

```css
workspace-tabs.is_continuous_mode:not(.mod-stacked) .markdown-preview-view img:not([width]), .markdown-rendered img:not([width]) {
    max-width: calc(100% - 2*var(--file-margins));
}
```
